### ISSUE TITLE
Issue in Crossfilter top and group methods

### ISSUE THREAD

**Issue by shijocj** [crossfilter/crossfilter#163] opened 2021-04-07 10:13 UTC
I am working on crossfilter version 1.3.12. Here I have 2 dimensions, one as group dimension and other one is sort dimension.

```js
var groupDimension = cf.dimension(function(d) { return d.ELEMENT + " : "+ d.NOMDY});

var sortDimension = cf.dimension(function(d) { return d.ELEMENT });
```

Here first I am applying filter on groupDimension like as below
```js
groupDimension.filterExact(d); // here d is "1DP - DNL747: 0 mg/kg/dose : 86".
```

Then I take `sortDimension.top(Infinity)`
 
I got the result as below

```js
[{"SEX":"Male","NOMDY":86,"STRESN":149,"ELEMENT":"1DP - DNL747: 0 mg/kg/dose"},
{"SEX":"Male","NOMDY":86,"STRESN":151,"ELEMENT":"1DP - DNL747: 0 mg/kg/dose"},
{"SEX":"Male","NOMDY":86,"STRESN":175,"ELEMENT":"1DP - DNL747: 0 mg/kg/dose"},
{"SEX":"Male","NOMDY":86,"STRESN":107,"ELEMENT":"1DP - DNL747: 0 mg/kg/dose"},
{"SEX":"Male","NOMDY":86,"STRESN":166,"ELEMENT":"1DP - DNL747: 0 mg/kg/dose"}]
```

But when I find `sortDimension.group().all()`

I got result as 

```js
[{"key":"1DP - DNL747: 0 mg/kg/dose","value":4},
{"key":"2DP - DNL747: 10 mg/kg/dose","value":0},
{"key":"3DP2 - DNL747: 20 mg/kg/dose","value":0},
{"key":"4DP - DNL747: 100 mg/kg/dose","value":1},
{"key":"Predose","value":0}]
```

Actually `sortDimension.group().all()`  result is wrong, because in `sortDimension.top(Infinity)` I am getting 5 values, that all are 
"1DP - DNL747: 0 mg/kg/dose" element, but in sortDimension.group().all() method return "1DP - DNL747: 0 mg/kg/dose" count as 4 , "4DP - DNL747: 100 mg/kg/dose" count as 1 and other elements count as zero.

When I verified in data `sortDimension.top(Infinity)` method working as correct, but the `sortDimension.group().all()` method giving wrong result.

![image](https://user-images.githubusercontent.com/9246197/113849784-6ee14b00-97b7-11eb-8794-ade9aa05e6cc.png)

**Comment by gordonwoodhull** [comment] 2021-04-07 11:26
When you file an issue, please specify the expected result. You don't say what you think is wrong here, you just describe the actual result in words. It is also important to include a sample data set which reproduces the failure.

I think you are saying that since the `.top()` result returns only rows containing `"ELEMENT":"1DP - DNL747: 0 mg/kg/dose"`, the value for `sortDimension.group().all()` with key `"4DP - DNL747: 100 mg/kg/dose"` should be 0.

You probably have nulls or NaNs, or other unsortable data which are causing sorting to fail. Please see [this entry in the wiki](https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#natural-ordering-of-dimension-and-group-values) for hints.

**Comment by gordonwoodhull** [comment] 2021-04-07 12:12
I'm going to close this, but please comment if the linked article doesn't help.

**Closed by gordonwoodhull** 2021-04-07 12:12 UTC
