### ISSUE TITLE
"Maximum call stack size exceeded", on dimension operation of large json file

### ISSUE THREAD

**Issue by keyscores** [crossfilter/crossfilter#61] opened 2016-08-11 23:36 UTC
I have an 8Mb JSON file, approximately 27K rows. The rows are not always uniform. Some rows might lack a dimension, or that dimension may be 'undefined' or NaN. 

The very first operation makes the script fail. It's a simple dimension assignment:
`var dimension = cf.dimension(function(fact) { return fact.title ; });
`
I would assume the iterator function 'return fact.title' would already account for undefined types, and exclude. 

Is this a bug, or is there a step I'm missing?

I see a similar issue in the square/crossfilter repo: https://github.com/square/crossfilter/issues/27

**Comment by gordonwoodhull** [comment] 2016-08-11 23:49
Hi @keyscores, yes it sounds like you have diagnosed your problem correctly. You need to sanitize your data before passing it to crossfilter, because crossfilter needs data that is strictly ordered, and NaNs are not.

The library was designed this way because any checks would significantly slow it down.

No, the dimension accessor function does not exclude any values. It is just trying to find a key to index by.

In this particular case, you might be able to sanitize on the fly:

```js
return fact.title || '';
```

But it may be faster just to preprocess your data in a loop.

**Comment by keyscores** [comment] 2016-08-12 00:08
Thanks @gordonwoodhull  That is quite helpful. It would be great to see this in the docs. 

Perhaps there could be some error handling to catch these cases. 

Also I would propose that the library have a fail-safe mode for heterogeneous data. It doesn't seem to slow down the code to add the   || "" ; Are there any other performance penalties to catching these situations?

**Comment by gordonwoodhull** [comment] 2016-08-12 02:37
It says it pretty firmly in the documentation for this function:

> crossfilter.<b>dimension</b>(<i>value</i> [, <i>isArray</i>])
> Constructs a new dimension using the specified *value* accessor function. **The function must return naturally-ordered values**, *i.e.*, values that behave correctly with respect to JavaScript's `<`, `<=`, `>=` and `>` operators.

I'm not really sure what a safe mode would buy us. It would hide some real problems in data, which are better handled by explicit preprocessing because then the assumptions about invalid values are in the code. I think it's better for the library to fail than to mislead.

**Comment by gordonwoodhull** [comment] 2016-08-12 02:40
Since this really is the same issue which has been covered a number of places, I'm going to close this. Feel free to open another issue if you have a concrete proposal.

**Closed by gordonwoodhull** 2016-08-12 02:40 UTC

**Comment by esjewett** [comment] 2016-08-12 13:12
I agree with @gordonwoodhull's comments.

One thing we possibly could do is put some heuristic checks in to the dimension accessor setter. For example, we could check the accessor function that the user provides against a variety of values and make sure that the values that come out are always naturally-ordered. If they are not, then we could put a warning on the console. I'm not really a fan of this idea, but it could be workable. Food for thought.

**Comment by keyscores** [comment] 2016-08-12 18:05
I appreciate the comments.
My only suggestion is that the docs somewhere say clearly that the data should be uniform or handled in your function. I can't say that the docs pointed out by @gordonwoodhull are obvious to me.
Secondly, I think "Maximum call stack size exceeded" is not a particularly helpful error. I would propose that specific error handling would be helpful. Currently it's quite hard to debug even when you know about this edge case.
I'm new to crossfilter, so apologies in advance if you have heard this before.

**Comment by esjewett** [comment] 2016-08-13 22:49
Unfortunately we don't have any control over the error message. The call stack growing out of control is just what happens with a quicksort when there is no natural ordering of the objects being sorted (I believe).

Definitely open to suggestions for updating the docs to be more helpful. Maybe we could provide an example. If you're up for it and would like to suggest some wording, that would be awesome!

**Comment by hirako2000** [comment] 2018-08-10 21:21
I understand the approach, and why this got closed, but really sanitazing ain't always an option before run time. 
The process is meant to be fast so avoiding the check is sound, but ideally there should be an option for safe checking (at the expense of performance) so that this doesn't happen. Skipping the comparison with a warning/info.
A stack call limit imo is a bug.

**Comment by gordonwoodhull** [comment] 2018-08-10 21:47
Right, we have the open enhancement issue #69, to provide validation as a preprocessing step. It may not be too hard, I just haven't had time to implement it and no one has contributed it.

I am certain that it would be too slow to add it as part of the sorting algorithm. That's too late.

I don't think there is any "call stack limit" with valid data. I believe the issue is that the algorithm is recursive and if its preconditions are violated, it recurses infinitely and dies.

**Comment by esjewett** [comment] 2018-08-10 22:37
Correct, I think. If someone wanted to contribute a check, it should happen during the step of adding new data. Each dimension would need to keep track of what type of value was returned by its accessor for all previously added records and throw an error in the event that the accessor returns a value that isn't naturally order-able compared to other values that have been returned in the past.

**Comment by hirako2000** [comment] 2018-08-11 12:59
Thanks for your input and fast response @gordonwoodhull / @esjewett .
I managed to simply sanitise before sending it off to crossfilter. I have to say this lib is awesome, the performance is truly fantastic and I understand the decisions made to focus on that.

I don't know the ins and outs of the src so it would take me some time to make a sound contribution, I have to finish up a POC, after that I can look into it see if I can add the flag.
